name: Build manylinux wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BEFORE_ALL_LINUX: "yum install -y boost boost-thread boost-devel && python -m pip install --upgrade pip"
          CIBW_ARCHS_LINUX: "auto64"
          CIBW_SKIP: "*-musllinux_* cp36-*"

      - uses: actions/upload-artifact@v2
        with:
          name: confseq_manylinux_wheels
          path: ./wheelhouse/*.whl
