name: Publish package to PyPi
on: [push]
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish a Python distribution to PyPI
    # Only publish package for tagged commits and on Steve Howard's repo (not forks)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository_owner == 'gostevehoward'
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      user: __token__
      password: ${{ secrets.PYPI_API_TOKEN }}
